apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xs6o
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xs6o
    app.kubernetes.io/part-of: tkrw-pr714-0075-0001-app
  name: devfile-sample-xs6o
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xs6o
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xs6o
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0001-tenant/tkrw-pr714-0075-0001-app/devfile-sample-xs6o@sha256:c17c041a9a45682709370c095573c78cfc8c592dcb91de8eb2ea4de66bc491be
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
